name: Build code, run unit test, run SAST, SCA, DAST security scans

on: 
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run unit tests and SAST scan on the source code 
    steps:
      - uses: actions/checkout@v2
      
      # Setting up Java environment
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      
      # Building and scanning with SonarCloud
      - name: Build with Maven cloud
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=devsecops-github-actions-pj -Dsonar.organization=devsecops-github-actions-pj -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  security:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: build
    name: Deploy and perform SCA scan on Dev
    environment: 
      name: dev
      url: 'http://dev.myapp.com'
    steps:
      - uses: actions/checkout@v2
      
      # Scanning for vulnerabilities with Snyk
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  DAST:
    runs-on: ubuntu-latest
    needs: security
    name: DAST Scan on API Endpoint
    steps:
      # Running DAST scan with Dastardly
      - name: Run Dastardly Action Step
        continue-on-error: true
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://ginandjuice.shop'
      
      # Parsing and publishing the JUnit report
      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/dastardly-report.xml'
          require_tests: true
